#! /usr/bin/env python3
import sys
MIN_PYTHON = (3, 6)
if sys.version_info < MIN_PYTHON:
    sys.exit("Python %s.%s or later is required.\n" % MIN_PYTHON)

import os
lib_path = os.path.relpath('etmMVC/')
sys.path.append(lib_path)

from etmMVC.model import setup_logging, logger, about
from etmMVC.view_pt import main
log_levels = [str(x) for x in range(1, 6)]


if __name__ == "__main__":
    loglevel = 2 # info
    homedir = os.path.expanduser("~")
    etmdir = os.path.normpath(os.path.join(homedir, ".etm-mv"))



    if len(sys.argv) > 1 and sys.argv[1] in log_levels:
        loglevel = sys.argv.pop(1)
    if len(sys.argv) > 1 and os.path.isdir(sys.argv[1]):
        etmdir = sys.argv.pop(1)

    logdir = os.path.normpath(os.path.join(etmdir, 'logs'))
    if not os.path.isdir(logdir):
        os.makedirs(logdir)

    bakdir = os.path.normpath(os.path.join(etmdir, 'backups'))
    if not os.path.isdir(bakdir):
        os.makedirs(bakdir)

    setup_logging(loglevel, logdir)
    logger.info(about()[1])

    main(etmdir)

