#!/usr/bin/env python3

import sys, os
import email
import subprocess
import urllib.parse

# muttrc macro to pipe message to this script:
# macro index,pager Ce ";<pipe-message>inbasket<enter>" "pipe mail to etm inbasket"

etmhome = os.environ.get("ETMHOME")
if not etmhome:
    print("The environmental variable 'ETMHOME' is missing but required.")
    sys.exit()
elif not os.path.isdir(etmhome):
    print(f"The environmental variable 'ETMHOME={etmhome}' is not a valid directory.")
    sys.exit()

inbasket = os.path.join(etmhome, 'inbasket.text')

# Parse the email from standard input
message_bytes = sys.stdin.buffer.read()
message = email.message_from_bytes(message_bytes)

# Grab the relevant message headers
message_id = urllib.parse.quote(message['message-id'][1:-1])
subject = message['subject']

reminder = f"! {subject} @g open_in_mutt {message_id}"

with open(inbasket, 'a') as fo:
    fo.write(f"{reminder}\n")
print(f"appended:\n   '{reminder}'\nto {inbasket}")
